### ISSUE TITLE
TODO 截止到 24/07/07

### ISSUE THREAD

**Issue by Rbqwow** [MaaAssistantArknights/MaaAssistantArknights#9853]
# MAA TODO

Issue 太多啦，由于缺乏人手和新来的贡献者不知道有什么可做，就维护了一个 TODO 列表

帮帮牛牛——

## 新增

- [ ] 肉鸽支持自定义退出层数 #2674 #7058 #7972 PR #7219
- [ ] 完成后动作添加睡眠 #3218
- [ ] WPF GUI 指定材料支持自动选择关卡并导航 #3329 #4239 #5398
- [ ] 阻止**单** MAA 多开实例 #3767 #5171
- [ ] 定时关闭 #3658
- [ ] 自动战斗支持选择模组 #3710 #6959
- [ ] 支持更换基建副手 #3828 #4259 #8103
- [ ] 支持选择代理失败后的操作 #4846
- [ ] 扩展无限吃 48 小时内过期的理智药 #4849
- [ ] 更新日志中添加释放日期 #4863
- [ ] 完成后动作发送系统通知 #4882
- [ ] 一键搬活动商店 #6096
- [ ] 任务支持暂停 #2091 #6595 #7037 #9265
- [ ] 支持 socks5 代理 #6463
- [ ] 自动战斗支持替换干员 #8291
- [ ] 自动战斗支持自动借助战 #6023 #8463
- [ ] 通过检测注册表自动设置 MuMu 截图增强 #9076
- [ ] 自动隐秘战线 #9025
- [ ] 水月肉鸽支持领取委托奖励 #3262
- [ ] 水月肉鸽支持钥匙开宝箱 #4042
- [ ] 水月肉鸽支持抑制排异 #4147
- [ ] 肉鸽支持选择多结局 #3771 #7947 #8911
- [ ] 肉鸽等级满后自动停止 #3869
- [ ] 萨米肉鸽烧水考虑树篱及其他加成 #5706 #7941 #8639 #8639 #8841

## 修复

- [ ] [基建识别相关问题](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues?q=is%3Aopen+is%3Aissue+label%3A%22module%3A+infrast%22) ~~尤其是菲亚梅塔~~ ~~欠重构了~~
- [ ] 识别技能释放按钮和撤退干员按钮 而不是点击固定位置 #1332 #6746 #8473 #8529 #8657
- [ ] 多个 MAA 无法同时设置开机启动 #4031
- [ ] 肉鸽通关后卡住 #4183 #7792 #8976 #9179 #9506
- [ ] 干员头顶技能图标识别问题 #4502 #6370 #9171
- [ ] 阿米娅升变 #4740 #5550
- [ ] 支持自动去绿色化 #5043 #8392
- [ ] 干员识别和自动编队不会主动从头开始 #5179 #5257 #6341
- [ ] 自动更新重启不应该启动模拟器 #5653
- [ ] ~~主要是令的~~召唤物头像缓存问题 #6060 #6024 #9156
- [ ] 官服无法自动切换账号 #8104 #9064 #9161 #9339
- [ ] B 服无法自动切换账号 #7171
- [ ] 自动战斗跳过剧情问题 #7354 #9480
- [ ] B 服无法完成后退出客户端 #7779 #9349 PR #9352
- [ ] 莫名其妙出现一堆托盘图标 #8003
- [ ] 所有肉鸽都有可能莫名其妙卡在地图预览界面 #8781 #8792 #8984

## 优化

- [ ] 识别出错时获取前台 activity 检测游戏是否崩溃卡死或直接自动重启 登录失效 断线重连 等游戏本体异常检测问题 #1200 #2364 #2528 #2711 #3165 #3353 #3363 #3382 #3968 #4024 #4225 #4231 #4251 #4349 #4534 #4743 #5006 #5120 #5341 #5346 #5538 #5411 #5646 #5902 #6016 #7382 #7252 #7622 #7404 #7981 #8310 #8438 #8334 #8799 #8944
- [ ] 开始唤醒 支持识别游戏内热更新 #1240 #3598 #4218
- [ ] 指定关卡时 识别终端内上次作战以减少导航时间 #1179
- [ ] 拆分 `AllTasksCompleted` 为 `AllTasksCompleted` 和 `AllTasksEnded` #3213
- [ ] 仅一次 相关操作 #3432 #7231
- [ ] 没有公招凭证时也刷新空闲槽位 #4125
- [ ] 支持设置肉鸽难度 #3865 #6494 #8058 #8230 #8616 #8884 #8926 #9122 #9080
- [ ] 剿灭作战支持自选关卡及剿灭任务拆分 #4583 #5317 #6722 #8099
- [ ] 支持在战斗中开始任务 #4845
- [ ] 视频链接不替换作业分享站 #5349 ~~我也想要~~
- [ ] 检测网络波动时的加载动画 #6141
- [ ] 自动战斗漏怪自动退出 #6812
- [ ] 开始唤醒失败直接终止任务 #9159
- [ ] 真·异步上传企鹅物流和一图流 #9431
- [ ] 自动更新游戏客户端本体 #8123
- [ ] 动态切换无人机用途 #807 #4548 #5154
- [ ] 调！度！器！ #849 #3992 #3798 #4884 #5773 #6446 #7741 #7906 #8667 #9533

## 我觉得大家能讨论决策关不关或者分类的

- [ ] #3528
- [ ] #4383
- [ ] #4398
- [ ] #4494
- [ ] #4665
- [ ] #4826
- [ ] 自定义脚本 #5005 #6450
- [ ] 特别关注干员识别 #5213
- [ ] #5146
- [ ] 外部通知 #5098
- [ ] #5365
- [ ] CW-6 导航 #5618 #5719
- [ ] 通知这个已经修了吧(? #5750
- [ ] 卡剿灭总览也已经修了吧(? #5679
- [ ] ~~好久的 TODO~~ #5989 #5976
- [ ] #6154
- [ ] 引用了但是没关是什么鬼 #6400
- [ ] #6277
- [ ] #6918
- [ ] #6819
- [ ] #7053
- [ ] 掉落识别总滑动也修了吧(? #7381
- [ ] #7464
- [ ] #7967
- [ ] #8581
- [ ] #8727
- [ ] #8866
- [ ] #9113
- [ ] 算命像识别太快了 触底回弹还没弹回去 #9239

## 意见征集

- [ ] 半年以上且无法定位问题源无法处理的个别设备偶现 Issue 是否直接关闭 比如一堆的连接失败
- [ ] 基建相关意见请求是否列举一个 Won't Fix 列表
- [ ] MAA 总会将图片压缩到 720P 进行识别 源分辨率越高 出问题的几率越大 实测在非 720P 的源分辨率下干员识别已无法识别黍、红隼 对所有涉及到干员名识别的场景影响极大 #8139 #8583 #8605 #8801 #8821 #8957 #9134
- [ ] 活动关卡结束后关卡选择处理方式 #8744 #8910 #9118
- [ ] ~~MuMu 后台保活相关 是再和 MuMu 沟通 1 下 还是放弃~~
      沟通完毕 MuMu 提供了下文 3.1 提到的api

<details><summary>我的想法</summary>

> 0. 在测速时固定使用屏幕编号 0，启动方舟之后再用用户配置的屏幕编号  
   在下面那些之后想到的，貌似是不找 mumu 加 api 的最好办法了
> 1. 大前提：在勾选增强时先唤醒方舟再测截图，这个坎我没想到能咋绕
> 2. 开启增强时强制使用增强模式，跳过测速流程直接唤醒，忽略截图错误  
   屏幕编号写 1 时可以正常运行，改动最少，也可以不需要 0 作为前提，但是真截图出错没办法报错
> 3. 从 0 开始轮询屏幕编号，识别到方舟后在本次任务中记录编号并使用，下次任务重新轮询  
   只需要 MAA 做适配，不需要 MuMu 再改
>    1. 让 mumu 加一个通过屏幕编号获取包名的 api，或者反过来通过包名获取屏幕编号的 api  
      前者降低轮询识别难度，后者直接获取
>    2. 让 mumu 提供启动 app 并可以指定屏幕编号的 api  
      本意也是直接获取，但是烂活，如果用户自己启动还是不行
>    3. 给方舟单独固定一个屏幕编号，但这样其他游戏或许也得指定  
      固定值写死最简单，但是其他游戏不做可能会给 MuMu 上压力，或者只给方舟做被鹰角上压力
>
> 总结：大概就是 0 和 3.1 结合起来，先用 0 测速，然后启动方舟，再通过 api 使用包名找到 id
>
> 但后台保活在自动化场景下明显是个伪需求，并且多窗口触控还没有确定可用，MuMu 触控还没写，不如直接扔了，干脆写死 0 然后说不支持后台保活(√

</details>

- [ ] MuMu 开启高帧率模式也会出问题 截图太快会截到多出来的过渡动画帧 #9425
- [ ] MuMu 不能最小化启动 #9105 #9310
- [ ] 公招优先级策略 感觉像这样也得搞个完成后动作那种超级自选框了 #2718 #3818 #4885 #4980 #5312 #9119 #9069 #9319
- [ ] 完成后动作拆分 [#6477](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/6477#issuecomment-1857162548) #9545
- [ ] 多个 MAA 同时运行的问题 ~~我忘记录都有哪些 Issue 了~~

**Comment by Constrat** [comment]
@Rbqwow Super work. I suggest using - to order them
- #9853
and also /details

**Comment by Rbqwow** [comment]
> I suggest using - to order them
> 
> * [TODO 截止到 24/07/07 #9853](https://github.com/MaaAssistantArknights/MaaAssistantArknights/issues/9853)
>   and also /details

Originally I wrote it as `-` in vscode, and changed it to `- [ ]` when put it on github.
Personally I have no idea about it, just someone recommended to change it.

~~The TODO has finished several days ago but I just couldn't figure out where to put it.~~

**Comment by Constrat** [comment]
If it was already discussed, it's all good then!

**Comment by Rbqwow** [comment]
> perhaps we should also start closing BUG all issues created before 2024? or maybe a bit earlier as most are definitely outdated or dupicates as I've never seen anyone close an issue after it was fixed (not resposnsible)

I think we need to set up a bot that will close issue automatically when it's inactive for 180 days.
There are TOO many issues which are occasional and cannot reproduce.

**Comment by Constrat** [comment]
I think github-actions [bot] does that. I'll check and see. If you want to open an issue for the other devs MAA Team to discuss, or directly in the qq group ( I Can't join it XD)

**Comment by Rbqwow** [comment]
It's better when there's a label that can let an issue exempt from being closed.

**Comment by Constrat** [comment]
Yes there's an option for that.

**Comment by Saratoga-Official** [comment]
能补充个＃7617吗，我看好像没有

**Comment by Daydreamer114** [comment]
希望补充：
肉鸽多个相同职业预备干员导致干员选择异常：#9148 #9243 #9262 #9386 #9510

**Comment by status102** [comment]
- 给Mumu加了这个#9881 ，有没有好办法让用户强制测试（不测试也救不了就是

**Comment by liqfish** [comment]
希望maa能内置一个类似罗德岛助手app里的专精计算器功能
可以输入需要专精的干员并进行自动换班

**Comment by Saratoga-Official** [comment]
> 希望加一个继续任务的功能，目前的一键长草如果点了停止，再strat会把之前的动作重新进行一次。重新走基建换班有点耗时间（我的模拟器每次要花2分钟），加一个继续直接从刚刚停止的动作开始往后。

新增里任务支持暂停不就是吗
