### ISSUE TITLE
[Feature] Reclamation Algorithm for Yostar servers

### ISSUE THREAD

**Issue by Manicsteiner** [MaaAssistantArknights/MaaAssistantArknights#9992]
### 说说你遇到的问题？

<details>
<summary>Coming soon</summary>

![mcQ2u-6z6yK2sT3cSsg-fy 1](https://github.com/user-attachments/assets/bf6a5f22-e28c-4e05-9843-63b7545cd10c)

</details>

**TODO**:

- [x] Revert #8769 (have to be manually now), fix roguelike navigation
- [x] Unlock Reclamation Algorithm#2 for EN, KR and JP (txwy needs to wait)
- [x] Templates and texts for Reclamation Algorithm
- [x] Endless tests

**Comment by Constrat** [comment]
I hate this fucking mode

**Comment by HX3N** [comment]
Pre-preparation

I think we only need to add the image `Reclamation2SkipDays1.png`. Except for that, they are simply shapes

![Reclamation2SkipDays1](https://github.com/user-attachments/assets/959dc92d-1286-4bf4-bc14-55e004a35f53)

<details><summary>Arrange tasks in order (with image)</summary>

    "Reclamation2Begin": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["开", "始", "演", "算"],
        "roi": [844, 569, 436, 151],
        "next": ["#self", "#back"]
    },
![image](https://github.com/user-attachments/assets/d7bc93ec-577d-4b58-a8c8-d496dd3e3a07)

    "Reclamation2BeginPlotEnter": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["众人", "汇聚", "后舍"],
        "roi": [633, 239, 275, 156],
        "next": ["#self", "Reclamation2BeginPlotLoading@Reclamation2EnterStage"]
    },
![image](https://github.com/user-attachments/assets/aaeec443-7d8d-4e85-8276-f4d083ed89a8)

    "Reclamation2LeaveStageConfirm": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["确认", "离开"],
        "roi": [871, 407, 238, 146],
        "next": ["#back"]
    },
![image](https://github.com/user-attachments/assets/76dad085-49dc-4ff4-b572-f81d455a54d1)

    "Reclamation2CopiousCoppice": {
        "Doc": "进入丰饶灌木林，基地上方支线",
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["木", "林", "资源区"],
        "ocrReplace": [[".*源区", "资源区"]],
        "preDelay": 2000,
        "roi": [0, 171, 207, 144],
        "next": ["#self", "Reclamation2CopiousCoppiceBegin"]
    },
![image](https://github.com/user-attachments/assets/f2f2105b-a8ec-4c11-b15a-3c6b9b7aa722)

    "Reclamation2EnterStage": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["开始", "行动"],
        "roi": [1077, 499, 203, 146],
        "next": ["#back"]
    },
![image](https://github.com/user-attachments/assets/716bd1cf-f299-438d-96bd-1f644503a8b1)

    "Reclamation2Fight": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["开始", "行动"],
        "roi": [1029, 646, 222, 58],
        "next": ["Reclamation2FightConfirm"]
    },
![image](https://github.com/user-attachments/assets/d18e121c-74a6-4c3a-931b-22aa6e122f0d)

    "Reclamation2FightConfirm": {
        "Doc": "没人的时候会有弹窗",
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["确认"],
        "roi": [646, 447, 631, 64],
        "postDelay": 5000,
        "next": ["Stop"]
    },
![image](https://github.com/user-attachments/assets/23a18777-01be-4c3a-95e3-2404a7fb0920)

    "Reclamation2ClickDrop": {
        "Doc": "点击收取掉落物品",
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["行动", "结束"],
        "preDelay": 2000,
        "roi": [0, 158, 456, 201]
    },
![image](https://github.com/user-attachments/assets/31ad24e9-f1ff-472f-a84b-9292f31f9d28)

    "Reclamation2Birdland": {
        "Doc": "进入聚羽之地，基地左下支线",
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["聚羽", "之地", "捕猎区"],
        "preDelay": 2000,
        "roi": [598, 510, 262, 156],
        "next": ["#self", "Reclamation2BirdlandBegin"]
    },
![image](https://github.com/user-attachments/assets/cb0f37cc-2a37-4aaa-9816-5f37fc9584a1)

    "Reclamation2SkipDays2SkipTime": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["消磨", "时间"],
        "roi": [1071, 104, 208, 124],
        "sub": ["Reclamation2SkipDays2SkipTimeConfig", "Reclamation2SkipDays1"]
    },
![image](https://github.com/user-attachments/assets/b9c66f61-f36b-4a4b-b2e5-0abb567de813)

    "Reclamation2SkipDays2SkipTimeConfig": {
        "Doc": "消耗所有决断数",
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["确认"],
        "roi": [646, 447, 631, 64]
    },
![image](https://github.com/user-attachments/assets/aabd7472-9188-4008-a243-4a85bbb26824)

    "Reclamation2SkipDaysAward2": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "roi": [506, 609, 272, 111],
        "preDelay": 1000,
        "postDelay": 4000,
        "text": ["点击", "任意处", "继续"],
        "next": ["Reclamation2SkipDaysBeginNewDay"]
    },
![image](https://github.com/user-attachments/assets/56653e7f-759b-444b-bcec-d61f8bba0315)

    "Reclamation2SkipDaysBeginNewDay": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["开", "启", "今", "日"],
        "preDelay": 1000,
        "roi": [519, 525, 261, 144]
    },
![image](https://github.com/user-attachments/assets/839777d7-f4c0-417b-b579-17495688d9ea)

    "Reclamation2DeleteArchiveEnter": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["删除"],
        "roi": [1063, 550, 182, 123],
        "sub": ["Reclamation2DeleteArchiveConfirm*2"]
    },
![image](https://github.com/user-attachments/assets/71c36cf6-f99f-4ec6-be0b-d35ebafaa8e8)

    "Reclamation2DeleteArchiveConfirm": {
        "algorithm": "OcrDetect",
        "action": "ClickSelf",
        "text": ["确认", "删除"],
        "roi": [820, 406, 308, 146]
    },
![image](https://github.com/user-attachments/assets/84fb847d-84be-46d3-97c6-e057a79680e8)

</details>

**Comment by Constrat** [comment]
@HX3N casually doing god's work 🙏🏻 .
(Ready to see how Yostarn will completely fuck up the translations and the interface :))

**Comment by HX3N** [comment]
I checked, and `Reclamation2ExClickProduct` works fine even if the equipment name is written in Korean
~nvm that the ocr recognition isn't working well~. might need ocrReplace
